contact_form_site:
    path: /contact_form
    defaults: { _controller: Instride\Bundle\ContactFormBundle\Controller\ContactFormController::contactFormAction }

contact_form_subsite:
    path: /{prefix}/contact_form
    requirements:
        prefix: '[^/]+(?:/[^/]+)*'
    defaults: { _controller: Instride\Bundle\ContactFormBundle\Controller\ContactFormController::contactFormAction }
